use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 3
  total_round_num: 200
  save_to: "checkpoints/llama.cwq.webqsp.adpt2.dp2.fedbiot_nokg.ckpt"
  save_freq: 50
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'cwq@llm'
  splits: [0.8, 0.1, 0.1]
  splitter: 'iid'
  args: [ {
    'train_file': 'CWQ/ComplexWebQuestions_train.json',
    'val_file': 'CWQ/ComplexWebQuestions_dev.json'
  } ]
llm:
  grad_accum_step: 2
  tok_len: 800
  chat:
    max_len: 300
  model_parallel:
    use: True
    device_map: 'balanced_layers'
    same_device_map: False
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05 } ]
  kg_adapter:
    use: False
  offsite_tuning:
    use: True
    save_full_model: True
    emu_l: 0
    emu_r: 30
    strategy: 'drop_layer'
    kwargs: [ { 'drop_ratio': 0.2 }]
    emu_align:
      use: True
      initial_only: True
      periodic: True
      periodic_interval: 1
      periodic_start_round: 0
      periodic_save: False
      sim_loss: 'l2'
      layerwise_distill: False
      kl_divergence: 'raw'
      data:
        root: data/
        type: 'webquestionssp@llm'
        splits: [0.9, 0.1, 0.0]
        splitter: 'iid'
        args: [ {
          'train_file': 'WebQSP/data/WebQSP.train.json',
          'test_file': 'WebQSP/data/WebQSP.test.json'
        } ]
      train:
        local_update_steps: 5
        initial_update_rounds: 50
        lm_loss_weight: 0.0
        kd_loss_weight: 0.9
dataloader:
  batch_size: 1
model:
  type: '/home/async/data-disk/wgh/FedKG/federatedscope/llm/data/models/Llama-2-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    type: AdamW
    lr: 0.0001
    betas: (0.9, 0.95)
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 10
  metrics: ['loss']
  best_res_update_round_wise_key: 'val_loss'
  kgqa:
    split: 'val'
    match_mode: 'contains'
  report: ['weighted_avg', 'avg', 'raw']
  count_flops: False
expname: "fedbiot/llama-7b_cwq_webqsp_offsite_adpt2_dp2_nokg"
